Rst fix for missing classes (#636)
* stach fix

* fixed data_aug.rst

* stash

* add more classes

* add index

* add selector

* add types

* add vocabulary

* move vocabulary to the right rst

* fixed rst

* commit

* black

* pylint

* fix docstrings for added classes

* Error in code-block directive:

* docstring of forte.processors.data_augment.algorithms.typo_replacement_op.TypoReplacementOp:1:duplicate object description of forte.processors.data_augment.algorithms.typo_replacement_op.TypoReplacementOp, other instance in code/data_aug, use :noindex: for one of them

* AttributeError: module 'forte.process_job' has no attribute 'ProcessManager'

* Title underline too short.

* Fix

* fix

* Unexpected indentation

* Error in code-block directive:

* rst:33:Unexpected indentation.

* fix

* black and pylint

* black without hook

* error while formatting signature for forte.data.base_pack.PackType: 'TypeVar' object has no attribute '__mro__'

* remove pack type as a class

* remove type

* remove invalid hyperlinks

* fix docs

* fixed misspelled words

* black

* spell